---
name: test latest image

on:
  push:
    branches: ['*']
  schedule:
  - cron: 0 0 1 * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test_latest_image:

    strategy:
      matrix:
        dataset: ['1', '2']
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tree

    - name: pull docker image
      run: docker pull bids/dparsf:latest

    - name: print help and version
      run: |
        docker run -t --rm --read-only \
              bids/dparsf:latest --help
        docker run -t --rm --read-only \
              bids/dparsf:latest -v

    - name: get data
      run: |
        wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/utils/get_data_from_osf.sh
        bash get_data_from_osf.sh ds114_test${{ matrix.dataset }}

    - name: prepare output dir
      run: |
        mkdir -p ${HOME}/outputs${{ matrix.dataset }}

    - name: participant 01
      run: |
        docker run -t --rm \
        -v ${HOME}/data/ds114_test${{ matrix.dataset }}:/bids_dataset \
        -v ${HOME}/outputs${{ matrix.dataset }}:/outputs \
          bids/dparsf:latest \
            /bids_dataset /outputs participant \
            --participant_label 01

    - name: participant 02
      run: |
        docker run -t --rm \
        -v ${HOME}/data/ds114_test${{ matrix.dataset }}:/bids_dataset \
        -v ${HOME}/outputs${{ matrix.dataset }}:/outputs \
          bids/dparsf:latest \
            /bids_dataset /outputs participant \
            --participant_label 02

    - name: check output
      run: tree ${HOME}/outputs${{ matrix.dataset }}
